site_name: Write2Audiobook
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
repo_url: https://github.com/greg-martinez44/write2audiobook
edit_uri: https://github.com/greg-martinez44/write2audiobook/edit/gh-docs/docs/
nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - About:
    - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md
    - License: about/license.md

copyright: Copyright &copy; 2023 De Angelis Domenico Francesco.

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true