site_name: Write2Audiobook
theme: readthedocs
repo_url: https://github.com/greg-martinez44/write2audiobook
edit_uri: https://github.com/greg-martinez44/write2audiobook/edit/gh-docs/docs/
nav:
  - Home: index.md
  - About:
    - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md
    - License: about/license.md

copyright: Copyright &copy; 2023 De Angelis Domenico Francesco.

