site_name: Write2Audiobook
site_description: Project documentation for Write2Audiobook.

repo_url: https://github.com/greg-martinez44/write2audiobook
edit_uri: edit/gh-docs/docs/

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top

nav:
  - Home: index.md
  - Quick start: quick-start.md
  - User guide:
    - Download the scripts: user-guide/download-scripts.md
    - Install libraries: user-guide/install-libraries.md
    - Text files: user-guide/text-to-audio.md
    - Word documents: user-guide/docx-to-audio.md
    - PowerPoint presentations: user-guide/pptx-to-audio.md
    - Ebooks: user-guide/ebook-to-audio.md
  - About:
    - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md
    - License: about/license.md

copyright: Copyright &copy; 2023 De Angelis Domenico Francesco.

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true