name: deploy-pages-from-pr

on:
  pull_request:
    branches: main
    types: ["closed"]
    paths: ["docs/**", "mkdocs.yml"]

jobs:
  receive-pull-request:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Confirm run
        run: echo "Workflow run on ${{ github.event.number }}"
