name: deploy-pages-from-push

on:
  push:
    branches: ["main", "gh-docs"]
    paths: ["docs/**", "mkdocs.yml"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy-pages.yml
